### ISSUE TITLE
Document and understand API

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WARClight#9]
Blacklight has a [pretty robust JSON API](https://github.com/projectblacklight/blacklight/wiki/JSON-API), which we should understand and eventually document. Could be nice to imagine people using the API to grab content, text, etc. for their own research projects.

**Comment by ghost** [comment]
+1

That might be another argument in favour of exposing individual record views. Currently, a user can get the JSON of their search results (e.g. http://206.167.183.39/catalog.json?utf8=%E2%9C%93&search_field=all_fields&q=shakespeare), but can't easily get at the JSON for an individual record, should they want that. In a full record view, like with the results, just adding .json to the path will return the JSON for the full record.
